AWSTemplateFormatVersion: 2010-09-09
Description: SNS topic and endpoint
Parameters:
  SNSEndpointEmail:
    Type: String
  SNSEndpointType:
    Type: String
    Description:  SNSEndpointType
    Default: 'email'

Resources:
  CloudWatchSNS: 
   Type: AWS::SNS::Topic
   Properties: 
     Subscription: 
       - Endpoint: !Ref SNSEndpointEmail
         Protocol: !Ref SNSEndpointType

Outputs: 
  SNSTopicArn: 
    Description: Arn of SNS Topic
    Value: !Ref CloudWatchSNS
    Export:
      Name: SNSTopicArn